/** @type {import('tailwindcss').Config} */
// Build-time Tailwind (precompiled CSS) — menggantikan CDN runtime supaya RINGAN
// di tablet jadul & tetap rapi saat OFFLINE. Token = persis dari index.html lama.
// Plugin SAMA dgn CDN (?plugins=forms,container-queries) supaya tampilan identik.
import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#454747',
        'surface-bright': '#fcf9f8',
        'on-secondary-container': '#6f5400',
        'on-primary-fixed': '#410000',
        'on-surface-variant': '#5c403b',
        'on-surface': '#1c1b1b',
        surface: '#fcf9f8',
        'surface-container': '#f0eded',
        'surface-tint': '#be0f09',
        'tertiary-fixed': '#e2e2e2',
        'surface-dim': '#dcd9d9',
        'inverse-primary': '#ffb4a8',
        primary: '#b50303',
        background: '#fcf9f8',
        'surface-variant': '#e5e2e1',
        'on-tertiary-fixed': '#1a1c1c',
        'on-secondary-fixed-variant': '#5a4300',
        'primary-fixed-dim': '#ffb4a8',
        'error-container': '#ffdad6',
        'surface-container-high': '#eae7e7',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#251a00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#707171',
        'secondary-fixed': '#ffdf99',
        'on-tertiary-container': '#f6f7f7',
        'surface-container-low': '#f6f3f2',
        outline: '#916f6a',
        'on-background': '#1c1b1b',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'outline-variant': '#e6bdb7',
        'tertiary-fixed-dim': '#c6c6c7',
        'primary-fixed': '#ffdad4',
        'on-primary-fixed-variant': '#930001',
        'inverse-on-surface': '#f3f0ef',
        'inverse-surface': '#313030',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#ffc72c',
        'secondary-fixed-dim': '#f6bf22',
        'surface-container-highest': '#e5e2e1',
        'on-secondary': '#ffffff',
        'primary-container': '#da291c',
        'on-primary-container': '#fff5f3',
        'on-primary': '#ffffff',
        secondary: '#775a00',
        tertiary: '#575959',
        corney: { DEFAULT: '#b50303', dark: '#930001', light: '#fff5f3', ink: '#1c1b1b' },
      },
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', full: '9999px' },
      spacing: {
        'min-tap-target': '52px',
        'margin-page': '32px',
        'padding-card': '20px',
        'gutter-grid': '24px',
        'stack-gap': '16px',
        base: '8px',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans'],
        'display-lg': ['Plus Jakarta Sans'],
        'label-md': ['Plus Jakarta Sans'],
        'label-lg': ['Plus Jakarta Sans'],
        'body-lg': ['Plus Jakarta Sans'],
        'body-md': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        'display-md': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'headline-lg': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-md': ['14px', { lineHeight: '18px', fontWeight: '600' }],
        'label-lg': ['16px', { lineHeight: '20px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['22px', { lineHeight: '28px', fontWeight: '700' }],
        'display-md': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '800' }],
      },
    },
  },
  plugins: [forms, containerQueries],
}
